library(Seurat)
library(scRepertoire)
library(ggplot2)
library(cowplot)
library(scater)
library(scran)
library(dplyr)
library(Matrix)
#library(muscat)
library(reshape2)
library(celldex)
library(BiocParallel)
library(BiocNeighbors)
library(data.table)
library(DEsingle)
library(stringr)
library(sva)
library(readxl)
library(DESeq2)
library(DESeq)
library(pamr)
library(ggpubr)
library(ggraph)
library(gplots)
library(pca3d)
library(rgl)
library(scatterplot3d)
library(FactoMineR)
library(ggfortify)
library(useful)
library(tidyverse)
library(kableExtra)
library(xfun)
library(psych)
library(limma)
library(calibrate)
library(pheatmap)
library(ggraph)
library(circlize)
library(scales)
#add seurat
setwd("~/gse162498")

Only_T <- readRDS(file="Only_T_cluster_id_test.rds") 
DimPlot(Only_T, reduction = "umap", label = TRUE, pt.size = 0.5) 
DimPlot(Only_T, reduction = "umap", label = FALSE, pt.size = 0.5) 
table(Idents(Only_T))

#细胞及细胞中基因与RNA数量
slotNames(Only_T)
#assay
Only_T@assays
dim(Only_T@meta.data)
View(Only_T@meta.data)

#each type of cells
Naive_CD4_T<-subset(Only_T, idents=c('Naive_CD4_T'))
DimPlot(Naive_CD4_T, reduction = "umap")
saveRDS(Naive_CD4_T, file="Naive_CD4_T.rds")

Natural_Killer_T<-subset(Only_T, idents=c('Natural_Killer_T'))
DimPlot(Natural_Killer_T, reduction = "umap")
saveRDS(Natural_Killer_T, file="Natural_Killer_T.rds")

T_Helper<-subset(Only_T, idents=c('T_Helper'))
DimPlot(T_Helper, reduction = "umap")
saveRDS(T_Helper, file="T_Helper.rds")

Effector_Memory_CD4_T<-subset(Only_T, idents=c('Effector_Memory_CD4_T'))
DimPlot(Effector_Memory_CD4_T, reduction = "umap")
saveRDS(Effector_Memory_CD4_T, file="Effector_Memory_CD4_T.rds")

Resident_Memory_CD8_T<-subset(Only_T, idents=c('Resident_Memory_CD8_T'))
DimPlot(Resident_Memory_CD8_T, reduction = "umap")
saveRDS(Resident_Memory_CD8_T, file="Resident_Memory_CD8_T.rds")

Terminally_Exhausted_CD8_T<-subset(Only_T, idents=c('Terminally_Exhausted_CD8_T'))
DimPlot(Terminally_Exhausted_CD8_T, reduction = "umap")
saveRDS(Terminally_Exhausted_CD8_T, file="Terminally_Exhausted_CD8_T.rds")

Regulatory_T<-subset(Only_T, idents=c('Regulatory_T'))
DimPlot(Regulatory_T, reduction = "umap")
saveRDS(Regulatory_T, file="Regulatory_T.rds")

Cytotoxic_CD8_T<-subset(Only_T, idents=c('Cytotoxic_CD8_T'))
DimPlot(Cytotoxic_CD8_T, reduction = "umap")
saveRDS(Cytotoxic_CD8_T, file="Cytotoxic_CD8_T.rds")

Effector_Memory_CD8_T<-subset(Only_T, idents=c('Effector_Memory_CD8_T'))
DimPlot(Effector_Memory_CD8_T, reduction = "umap")
saveRDS(Effector_Memory_CD8_T, file="Effector_Memory_CD8_T.rds")

Pre_Exhausted_CD8_T<-subset(Only_T, idents=c('Pre_Exhausted_CD8_T'))
DimPlot(Pre_Exhausted_CD8_T, reduction = "umap")
saveRDS(Pre_Exhausted_CD8_T, file="Pre_Exhausted_CD8_T.rds")

#deg in Naive_CD4_T
Naive_CD4_T<-readRDS("Naive_CD4_T.rds")
a<-Naive_CD4_T@meta.data
write.table(a,"a")
class(Naive_CD4_T)
Naive_CD4_T.sec<-as.SingleCellExperiment(Naive_CD4_T)
group<-factor(c(rep(1,575),rep(2,4310)))

rds<-readRDS('Naive_CD4_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"results_Naive_CD4_T")
write.table(results.classified,"results.classified_Naive_CD4_T")

#deg in Natural_Killer_T
Natural_Killer_T<-readRDS("Natural_Killer_T.rds")
b<-Natural_Killer_T@meta.data
write.table(b,"b")
class(Natural_Killer_T)
Natural_Killer_T.sec<-as.SingleCellExperiment(Natural_Killer_T)
group<-factor(c(rep(1,3139),rep(2,3890)))

rds<-readRDS('Natural_Killer_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"results_Natural_Killer_T")
write.table(results.classified,"results.classified_Natural_Killer_T")

#deg in T_Helper
T_Helper<-readRDS("T_Helper.rds")
c<-T_Helper@meta.data
write.table(c,"c")
class(T_Helper)
T_Helper.sec<-as.SingleCellExperiment(T_Helper)
group<-factor(c(rep(1,1791),rep(2,1317)))

rds<-readRDS('T_Helper.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"T_Helper")
write.table(results.classified,"results.classified_T_Helper")

#deg in Effector_Memory_CD4_T
Effector_Memory_CD4_T<-readRDS("Effector_Memory_CD4_T.rds")
d<-Effector_Memory_CD4_T@meta.data
write.table(d,"d")
class(Effector_Memory_CD4_T)
Effector_Memory_CD4_T.sec<-as.SingleCellExperiment(Effector_Memory_CD4_T)
group<-factor(c(rep(1,3226),rep(2,5101)))

rds<-readRDS('Effector_Memory_CD4_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"Effector_Memory_CD4_T")
write.table(results.classified,"results.classified_Effector_Memory_CD4_T")

#deg in Resident_Memory_CD8_T
Resident_Memory_CD8_T<-readRDS("Resident_Memory_CD8_T.rds")
e<-Resident_Memory_CD8_T@meta.data
write.table(e,"e")
class(Resident_Memory_CD8_T)
Resident_Memory_CD8_T.sec<-as.SingleCellExperiment(Resident_Memory_CD8_T)
group<-factor(c(rep(1,1674),rep(2,1248)))

rds<-readRDS('Resident_Memory_CD8_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"Resident_Memory_CD8_T")
write.table(results.classified,"results.classified_Resident_Memory_CD8_T")

#deg in Terminally_Exhausted_CD8_T
Terminally_Exhausted_CD8_T<-readRDS("Terminally_Exhausted_CD8_T.rds")
f<-Terminally_Exhausted_CD8_T@meta.data
write.table(f,"f")
class(Terminally_Exhausted_CD8_T)
Terminally_Exhausted_CD8_T.sec<-as.SingleCellExperiment(Terminally_Exhausted_CD8_T)
group<-factor(c(rep(1,2373),rep(2,2866)))

rds<-readRDS('Terminally_Exhausted_CD8_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"Terminally_Exhausted_CD8_T")
write.table(results.classified,"results.classified_Terminally_Exhausted_CD8_T")

#deg in Regulatory_T
Regulatory_T<-readRDS("Regulatory_T.rds")
g<-Regulatory_T@meta.data
write.table(g,"g")
class(Regulatory_T)
Regulatory_T.sec<-as.SingleCellExperiment(Regulatory_T)
group<-factor(c(rep(1,3675),rep(2,2160)))

rds<-readRDS('Regulatory_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"Regulatory_T")
write.table(results.classified,"results.classified_Regulatory_T")

#deg in Cytotoxic_CD8_T
Cytotoxic_CD8_T<-readRDS("Cytotoxic_CD8_T.rds")
h<-Cytotoxic_CD8_T@meta.data
write.table(h,"h")
class(Cytotoxic_CD8_T)
Cytotoxic_CD8_T.sec<-as.SingleCellExperiment(Cytotoxic_CD8_T)
group<-factor(c(rep(1,289),rep(2,731)))

rds<-readRDS('Cytotoxic_CD8_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"Cytotoxic_CD8_T")
write.table(results.classified,"results.classified_Cytotoxic_CD8_T")

#deg in Effector_Memory_CD8_T
Effector_Memory_CD8_T<-readRDS("Effector_Memory_CD8_T.rds")
i<-Effector_Memory_CD8_T@meta.data
write.table(i,"i")
class(Effector_Memory_CD8_T)
Effector_Memory_CD8_T.sec<-as.SingleCellExperiment(Effector_Memory_CD8_T)
group<-factor(c(rep(1,29),rep(2,966)))

rds<-readRDS('Effector_Memory_CD8_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"Effector_Memory_CD8_T")
write.table(results.classified,"results.classified_Effector_Memory_CD8_T")

#deg in Pre_Exhausted_CD8_T
Pre_Exhausted_CD8_T<-readRDS("Pre_Exhausted_CD8_T.rds")
j<-Pre_Exhausted_CD8_T@meta.data
write.table(j,"j")
class(Pre_Exhausted_CD8_T)
Pre_Exhausted_CD8_T.sec<-as.SingleCellExperiment(Pre_Exhausted_CD8_T)
group<-factor(c(rep(1,238),rep(2,223)))

rds<-readRDS('Pre_Exhausted_CD8_T.rds')
counts<-as.matrix(rds@assays$RNA@counts)
results<-DEsingle(counts=counts,group=group)
results.classified <- DEtype(results = results, threshold = 0.05)
write.table(results,"Pre_Exhausted_CD8_T")
write.table(results.classified,"results.classified_Pre_Exhausted_CD8_T")

#volcano_plot
setwd("~/gse162498/deg")
res <- read.csv("deg_Cytotoxic_CD8_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-6,7),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_Effector_Memory_CD4_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-6,7),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_Effector_Memory_CD8_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-6,8),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_Natural_Killer_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-6,7),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_Naive_CD4_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-6,7),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_Pre_Exhausted_CD8_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-6,7),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_T_Helper", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-6,7),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_Resident_Memory_CD8_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-6,7),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_Terminally_Exhausted_CD8_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-2,2),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)

res <- read.csv("deg_Regulatory_T", header=TRUE,sep="\t")
head(res)
with(res, plot(log2FoldChange, -log10(fdr), pch=20, main="Volcano plot", xlim=c(-7,7),col="grey"))
# Add colored points: red if pvalue<0.05, orange of log2FC>1, green if both)
#with(subset(res, fdr<.05 ), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="orange"))
with(subset(res, fdr<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(fdr), pch=20, col="blue"))
with(subset(res, fdr<.05 & log2FoldChange>1), points(log2FoldChange, -log10(fdr), pch=20, col="red"))
#with(subset(res, P.Value<.05 & abs(log2FC)>1), textxy(logFC, -log10(P.Value), labs=Gene, cex=.6))
abline(h=1.3,v=1,lty=3)
abline(v=-1,lty=3)
